### ISSUE TITLE
Error on package load: TimeArray type

### ISSUE THREAD

**Issue by multidis** [JuliaQuant/FinancialSeries.jl#1] opened 2015-02-09 03:25 UTC
```
using FinancialSeries
```

Warning: could not import Base.add! into FinancialSeries
ERROR: too many parameters for type TimeArray

Where does the definition `TimeArray{T,N,M}` live now with the 3rd parameter being metadata? I found only `TimeSeries.jl` metadata-branch but that code seems older and is indexed not in `DateTime`... Thanks for any help! (I am trying to reproduce this backtesting [gist](https://gist.github.com/milktrader/11094671)). Would love to use `quantstrat` functionality in Julia.

**Comment by milktrader** [comment] 2015-02-09 13:33
The metadata field is only in a branch of TimeSeries. I started an issue about adding it https://github.com/JuliaStats/TimeSeries.jl/issues/126

As you can see, there is not a lot of excitement for this new feature. I'm a bit reticent to add things to TimeSeries in general because of its goal of being a parsimonious package.

There is also the issue of whether it's useful to explicitly type the metadata field. 

FinancialBlotter and FinancialTimeSeries are still experimental I'm afraid. It wouldn't take too much work to get them up to registered package status though. A way to get this metadata functionality (if we want it) is to simply place it in a `FinancialTimeSeries` type, which is where I was headed last.

Reproducing quantstrat functionality in Julia is a long-term goal of mine, but I'm afraid I'm a one-man show!

**Comment by multidis** [comment] 2015-02-09 20:59
Thanks for clarifying about metadata; I can imagine that incorporating a fairly abstract component into `TimeSeries` type may affect compiler efficiency. Perhaps it is better to define more specific metadata for each use case.

Is [this](https://github.com/multidis/FinancialSeries.jl/blob/master/src/financialtimeseries.jl) along the lines of what you meant?

I understand that all existing code refers to `timestamp`, `values` slots in `FinancialTimeSeries` objects, but would it be better to use `TimeSeries` as a single component:

```
type FinancialTimeSeries
  tarray::TimeArray
  meta::AbstractInstrument
end
```

**Comment by milktrader** [comment] 2015-02-09 22:39
Yes, that's almost exactly the type. Here's the problem Suppose you want log returns of your time series. You will need to write `percentchange(fts::FinancialTimeSeries)` This is not a _big_ deal, even with having to duplicate the entire `TimeSeries` list of methods, but it's duplication. At this point, you may as well re-implement the entire `TimeSeries` module, including constructors and not require `TimeSeries` at all. 

If `TimeSeries` has a metadata field, all the methods would be free and there wouldn't be a need to create a separate `FinancialTimeSeries` type.

**Comment by multidis** [comment] 2015-02-10 23:12
Metadata should probably not be restricted to `AbstractInstrument` as in my previous example. Other examples could be sub-types of `AbstractCurrency`, or even some types of signals (?). Non-financial packages may do the same with their types.

Would this work:

```
type FinancialTimeSeries{T<:Float64, N, M<:Union(AbstractInstrument, AbstractCurrency)} <: AbstractTimeSeries
  ta::TimeSeries.TimeArray{T,N}
  instrument::M
end
```

Then access `TimeSeries` methods (write convenience access functions as needed):

```
using MarketData, FinancialSeries
q = FinancialTimeSeries(cl, Stock(Ticker("AAPL")))
percentchange(q.ta, method="log")
```

Blotter type defined similarly seems to result in [less code](https://github.com/multidis/FinancialBlotter.jl/blob/master/src/blotter.jl) with constructor function re-using TimeArray inner constructor checks. Show-method modifications are [easy](https://github.com/multidis/FinancialBlotter.jl/blob/master/src/show.jl#L3).

**Comment by milktrader** [comment] 2015-02-11 04:07
Yes, the convenience access functions are not too difficult. Instead of having the user select `q.ta` as in your example though, it would be better to define it this way:

``` julia
percentchange(fts::FinancialTimeSeries) = FinancialTimeSeries(percentchange(fts.series), fts.instrument)
```

And so forth. I changed the `ta` to `series` since it's more descriptive.

**Comment by multidis** [comment] 2015-02-11 22:58
Moving closer to a pull request but having problems with [wrapper functions](https://github.com/multidis/FinancialSeries.jl/blob/master/src/financialtimeseries.jl#L34) for `TimeArray` methods. Any idea what is wrong there?

```
methods(FinancialSeries.colnames)
```

1 method for generic function colnames:
    colnames{T,N,M}(fts::FinancialTimeSeries{T,N,M}) at ...

but then

```
FinancialSeries.colnames(aapl)
```

gives:
`colnames` has no method matching colnames(::FinancialTimeSeries{Float64,2,Stock})

**Comment by milktrader** [comment] 2015-02-21 02:23
Hmm, I'm not seeing this issue anymore. I'll close it assuming the new meta field in TimeArrays has resolved it. 

I haven't looked for where `FinancialSeries.colnames` is defined but it appears to be redundant now that we have identified it as an alias for TimeArray with specific meta types.

**Closed as completed by milktrader** 2015-02-21 02:23 UTC

**Comment by multidis** [comment] 2015-02-21 03:50
Indeed this problem was for previous type definition, irrelevant after `TimeSeries.jl` update.
